# JID to serve the responses from.
jid = "chatbot@xmpp.com"

# XMPP account password.
password = "<password>"

# Users allowed to use the chatbot.
allowed_users = ["alex@xmpp.com", "john@example.com"]

# OpenAI API base URL. Everything before `chat/completions` in the URL.
api_url = "https://api.openai.com/v1/"

# Optional `api-version` get parameter. Used by Azure endpoints.
#api_version = "2023-03-15-preview"

# Auth header `api-key: {api_key}`. Used by Azure endpoints.
# Only one of `api_key` / `api_token` must be set.
#api_key = "<API key>"

# Auth header `Authorization: Bearer {api_token}`. Used by OpenAI endpoints.
api_token = "<API token>"

# Model to use.
model = "gpt-4o-mini"

# Optional system message to initialize the model.
system_message = "You are a helpful assistant."

# Maximum number of tokens to keep in every conversation.
max_history_tokens = 2500
